export default function DashboardHome() {
  return (
    <div>
      <h1 className="text-2xl font-semibold leading-7 text-gray-900 -white">Dashboard</h1>
      
      <div className="mt-8 grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">
        {/* Mock Data Cards */}
        <div className="overflow-hidden rounded-lg bg-white px-4 py-5 shadow sm:p-6 -gray-800">
          <dt className="truncate text-sm font-medium text-gray-500 -gray-400">Total Campaigns</dt>
          <dd className="mt-1 text-3xl font-semibold tracking-tight text-gray-900 -white">12</dd>
        </div>
        <div className="overflow-hidden rounded-lg bg-white px-4 py-5 shadow sm:p-6 -gray-800">
          <dt className="truncate text-sm font-medium text-gray-500 -gray-400">Active Templates</dt>
          <dd className="mt-1 text-3xl font-semibold tracking-tight text-gray-900 -white">4</dd>
        </div>
        <div className="overflow-hidden rounded-lg bg-white px-4 py-5 shadow sm:p-6 -gray-800">
          <dt className="truncate text-sm font-medium text-gray-500 -gray-400">Products in Library</dt>
          <dd className="mt-1 text-3xl font-semibold tracking-tight text-gray-900 -white">1,402</dd>
        </div>
      </div>

      <div className="mt-8">
        <h2 className="text-base font-semibold leading-6 text-gray-900 -white">Recent Activity</h2>
        <div className="mt-4 overflow-hidden rounded-md bg-white shadow -gray-800">
          <ul role="list" className="divide-y divide-gray-200 -gray-700">
            <li className="px-6 py-4">
              <div className="flex space-x-3">
                <div className="flex-1 space-y-1">
                  <div className="flex items-center justify-between">
                    <h3 className="text-sm font-medium text-gray-900 -white">Summer Sale 2026 Poster exported</h3>
                    <p className="text-sm text-gray-500 -gray-400">1h ago</p>
                  </div>
                  <p className="text-sm text-gray-500 -gray-400">Generated by Admin User</p>
                </div>
              </div>
            </li>
            <li className="px-6 py-4">
              <div className="flex space-x-3">
                <div className="flex-1 space-y-1">
                  <div className="flex items-center justify-between">
                    <h3 className="text-sm font-medium text-gray-900 -white">Template &quot;A4 Grocery Offer&quot; created</h3>
                    <p className="text-sm text-gray-500 -gray-400">3h ago</p>
                  </div>
                  <p className="text-sm text-gray-500 -gray-400">Created by Admin User</p>
                </div>
              </div>
            </li>
          </ul>
        </div>
      </div>
    </div>
  );
}
